In [1]:
import torch
import torch.nn as nn
import torch.nn.functional as F
import torch.optim as optim

In [2]:
# 현재 실습하고 있는 파이썬 코드 재실행해도 다음에도 같은 결과가 나오도록 랜덤 시드 설정
torch.manual_seed(1)

In [3]:
# 실습을 위한 기본 셋팅 작업 완료 
# 훈련 데이터 x_train y_train 을 선언
x_train = torch.FloatTensor([[1],[2],[3]])
y_train = torch.FloatTensor([[2],[4],[6]])

# x_train 와 shape 출력
print("x_train, x_train_shape")
print(x_train)
print(x_train.size()) # or x_trian.shape
# x_train 값 x_trian size = 3x1

print("")
# y_train and y_train shape output
print("y_train, y_train_shape")
print(y_train)
print(y_train.shape)
# y_train 값  y_trian size = 3x1

x_train, x_train_shape
tensor([[1.],
        [2.],
        [3.]])
torch.Size([3, 1])

y_train, y_train_shape
tensor([[2.],
        [4.],
        [6.]])
torch.Size([3, 1])


In [4]:
# 가중치와 편향의 초기화 
# 선형 회귀란 학습 데이터와 가장 잘 맞는 하나의 직선을 찾는 일입니다.
# 그리고 가장 잘 맞는 직선을 정의하는 것은 바로 W and b 입니다.
# 선형희귀의 목표는 가장 잘 맞는 직선을 정의하는 W and b 입니다.

# 가중치 0으로 초기화하고 이 값을 출력 편향 b도 0으로 초기화
# requires_grad = True -> 학습을 통해 계속. 값이 변경되는 변수임을 의미합니다.
w = torch.zeros(1, requires_grad = True)
print("가중치 w : ", w)

b = torch.zeros(1, requires_grad = True)
print("편향 b : ", b)
# W 와 b 둘다 0 이므로 현 직선의 방정식 다음과 같습니다.
# 현재의 가중치 : y = 0 * x + 0 
# 지금 상태에선 x에 어떤 값이 들어가도 가설은 0을 예측하게 됩니다. 즉 아직 적절한 W와 b의 값이 아닙니다.

가중치 w :  tensor([0.], requires_grad=True)
편향 b :  tensor([0.], requires_grad=True)


In [5]:
# 가설 세우기 
# 파이토치 코드 상으로 직선의 방정식에 해당되는 가설을 선언
hypothesis = x_train * w + b
print("가설: \n", hypothesis)

가설: 
 tensor([[0.],
        [0.],
        [0.]], grad_fn=<AddBackward0>)


In [6]:
# loss fn 선언 하기 
# 평균 제곱 오차를 선언
loss = torch.mean((hypothesis - y_train) ** 2)
print(loss)

tensor(18.6667, grad_fn=<MeanBackward0>)


In [7]:
# 경사 하강법 구현 하기 
# input w b 가 sgd 의 입력이 됩니다.
optimizer = optim.SGD([w, b], lr = 0.01)
# SGD -> 경사 하강법의 일종입니다.

In [8]:
# 기울기 0으로 초기화
optimizer.zero_grad()

# loss fn 미분하여 기울기 계산
loss.backward()

# w 와 b 값을 업데이트
optimizer.step()

# 학습을 진행
epoch_num = 2000 # 원하는 만큼 경사 하강법을 반복

# epoch : 전체 훈련 데이터가 학습에 한 번 사용된 주기를 말합니다.
for epoch in range(epoch_num + 1):
    
    hypothesis = x_train * w + b
    
    loss = torch.mean((hypothesis - y_train) ** 2)
    
    # loss H(x) 개선
    optimizer.zero_grad()
    loss.backward()
    optimizer.step()
    
    # 100번 마다 print Epoch w b loss
    if epoch % 100 == 0:
        print("Epoch {:4d}/{} W : {:.3f} loss : {:.6f}"
        .format(epoch, epoch_num, w.item(),  b.item(),  loss.item()))

Epoch    0/2000 W : 0.353 loss : 0.150933
Epoch  100/2000 W : 1.746 loss : 0.576683
Epoch  200/2000 W : 1.801 loss : 0.453329
Epoch  300/2000 W : 1.843 loss : 0.356358
Epoch  400/2000 W : 1.877 loss : 0.280130
Epoch  500/2000 W : 1.903 loss : 0.220207
Epoch  600/2000 W : 1.924 loss : 0.173103
Epoch  700/2000 W : 1.940 loss : 0.136075
Epoch  800/2000 W : 1.953 loss : 0.106967
Epoch  900/2000 W : 1.963 loss : 0.084086
Epoch 1000/2000 W : 1.971 loss : 0.066099
Epoch 1100/2000 W : 1.977 loss : 0.051960
Epoch 1200/2000 W : 1.982 loss : 0.040845
Epoch 1300/2000 W : 1.986 loss : 0.032108
Epoch 1400/2000 W : 1.989 loss : 0.025240
Epoch 1500/2000 W : 1.991 loss : 0.019841
Epoch 1600/2000 W : 1.993 loss : 0.015597
Epoch 1700/2000 W : 1.995 loss : 0.012260
Epoch 1800/2000 W : 1.996 loss : 0.009638
Epoch 1900/2000 W : 1.997 loss : 0.007576
Epoch 2000/2000 W : 1.997 loss : 0.005956


In [9]:
# torch.manual_seed() 하는 이유
# 결론 : 사용한 프로그램의 결과는 다른 컴퓨터에서 실행시켜도 동일한 결과를 얻을 수 있습니다.
# 이유 : torch.manual_seed()는 난수 발생 순서와 값을 동일하게 보장해주는 특징

import torch
torch.manual_seed(3)
print("Random seed is 3")

# range (start , end) -> 출력 범위 지정
for i in range(1,3):
    print(torch.rand(1))

Random seed is 3
tensor([0.0043])
tensor([0.1056])


In [10]:
torch.manual_seed(3)
print("Random seed is 5")

for i in range(1,3):
    print(torch.rand(1))

Random seed is 5
tensor([0.0043])
tensor([0.1056])


In [11]:
# 자동미분 실습하기
import torch

# 값이 2인 임의의 스칼라 텐서 w 를 선언 이때 required_grad를 True로 설정합니다. 
# 이는 이 텐서에 대한 기울기를 저장하겠다는 의미입니다. 뒤에서 보겠지만, 이렇게 하면 w.grad에 w에 대한 미분값이 저장됩니다.
# 연산을 기록
w = torch.tensor(2.0, requires_grad=True)

# 2w^2 + 5 -> 8

# 수식 정의

y = w**2
z = 2*y + 5

# 이제 해당 수식을 w에 대해서 미분 BackWard()를 호출하면 해당 수식의 w에 대한 기울기 계산

z.backward()

print("수식을 w로 미분한 값 : {}".format(w.grad))

수식을 w로 미분한 값 : 8.0


In [12]:
import torch
import torch.nn as nn
import torch.nn.functional as F
import torch.optim as optim

torch.manual_seed(1)

# 다중 선형 회귀 실습
# 앞서 배운 x가 1개인 선형 회귀를 단순 선형 이라고 합니다.
# 이번 배울것은 다수의 x 로부터 y를 예측하는 다중 선형 회귀

# H(x) = w1x1 + w2x2 + w3x3 + b
x1_train = torch.FloatTensor([[73],[93],[89], [96], [73]])
x2_train = torch.FloatTensor([[80],[88],[91], [98], [66]])
x3_train = torch.FloatTensor([[75],[93],[90], [100], [70]])
y_train = torch.FloatTensor([[152],[185],[180], [196], [142]])

In [13]:
# 가중치 w와 편향 b를 선언 합니다. 가중치 w도 3개 선언
w1 = torch.zeros(1, requires_grad=True)
w2 = torch.zeros(1, requires_grad=True)
w3 = torch.zeros(1, requires_grad=True)
b =  torch.zeros(1, requires_grad=True)

In [14]:
# 가설 loss fn optim 선언 후 경사 하강법을 1000회 반복
optimizer = optim.SGD([w1, w2, w3, b], lr=1e-5)

epoch_num = 1000

for epoch in range(epoch_num + 1):
    
    # H(x) 계산
    # 가설을 선언하는 부분인 
    # hypothesis = x1_train * w1 + x2_train * w2 + x3_train * w3 + b에서도 x_train의 개수만큼 w와 곱해주도록
    hypothesis = x1_train * w1 + x2_train * w2 + x3_train * w3 + b
    
    loss = torch.mean((hypothesis - y_train) ** 2)
    
    # loss로 H(x) 개선
    optimizer.zero_grad() # 기울기를 0으로 초기화
    loss.backward() # loss 함수를 미분하여 기울기 계산
    optimizer.step() # w와 b 를 업데이트
    
    # 100번 마다 로그 출력 
    if epoch % 100 == 0:
        print("Epoch {:4d}/{} w1 {:.3f} w2 {:.3f} w3 {:.3f} b {:.3f} loss {:.6f}"
            .format(epoch, epoch_num, w1.item(),  w2.item(), w3.item(), b.item(), loss.item()))

Epoch    0/1000 w1 0.294 w2 0.294 w3 0.297 b 0.003 loss 29661.800781
Epoch  100/1000 w1 0.674 w2 0.661 w3 0.676 b 0.008 loss 1.563634
Epoch  200/1000 w1 0.679 w2 0.655 w3 0.677 b 0.008 loss 1.497603
Epoch  300/1000 w1 0.684 w2 0.649 w3 0.677 b 0.008 loss 1.435026
Epoch  400/1000 w1 0.689 w2 0.643 w3 0.678 b 0.008 loss 1.375730
Epoch  500/1000 w1 0.694 w2 0.638 w3 0.678 b 0.009 loss 1.319503
Epoch  600/1000 w1 0.699 w2 0.633 w3 0.679 b 0.009 loss 1.266215
Epoch  700/1000 w1 0.704 w2 0.627 w3 0.679 b 0.009 loss 1.215693
Epoch  800/1000 w1 0.709 w2 0.622 w3 0.679 b 0.009 loss 1.167821
Epoch  900/1000 w1 0.713 w2 0.617 w3 0.680 b 0.009 loss 1.122419
Epoch 1000/1000 w1 0.718 w2 0.613 w3 0.680 b 0.009 loss 1.079375


In [15]:
# 다중 선형 회귀 클래스 구현
import torch
import torch.nn as nn
import torch.nn.functional as F

torch.manual_seed(1)

In [16]:
# 데이터 생성
x_train = torch.FloatTensor([[73, 80, 75],
                            [93, 88, 93],
                            [89, 91, 90],
                            [96, 98, 100],
                            [73, 66, 70]])
y_train = torch.FloatTensor([[152], [185], [180], [196], [142]])

In [17]:
# class 생성
class MultivariateLinearRegressionModel(nn.Module):
    def __init__(self):
        super().__init__()
        self.linear = nn.Linear(3, 1) # 다중 선형 회귀이므로 input_dim = 3 , output_dim = 1
        
    def forward(self, x):
        return self.linear(x)
    

In [18]:
# model 정의
model = MultivariateLinearRegressionModel()

# optimizer 선언
optimizer = torch.optim.SGD(model.parameters(), lr = 1e-5)

In [19]:
# train 생성 
# 얼마 만큼 반복할 것 인가 ?!

epochs_num =2000
for epoch in range(epochs_num + 1):
    
    prediction = model(x_train)
    # model(x_train) == model.forward(x_train)
    
    loss = F.mse_loss(prediction, y_train) # 파이토치에서 제공하는 평균 제곱 오차 함수
    
    # loss 개선
    optimizer.zero_grad() # 기울기를 0으로 초기화
    loss.backward() # loss 함수를 미분하여 기울기 계산
    optimizer.step() # w와 b 를 업데이트
    
    # 100번 마다 로그 출력 
    if epoch % 100 == 0:
        print("Epoch {:4d}/{} loss : {:.6f}".format(epoch, epochs_num, loss.item()))

Epoch    0/2000 loss : 31667.597656
Epoch  100/2000 loss : 0.225993
Epoch  200/2000 loss : 0.223911
Epoch  300/2000 loss : 0.221941
Epoch  400/2000 loss : 0.220059
Epoch  500/2000 loss : 0.218271
Epoch  600/2000 loss : 0.216575
Epoch  700/2000 loss : 0.214950
Epoch  800/2000 loss : 0.213413
Epoch  900/2000 loss : 0.211952
Epoch 1000/2000 loss : 0.210559
Epoch 1100/2000 loss : 0.209230
Epoch 1200/2000 loss : 0.207967
Epoch 1300/2000 loss : 0.206762
Epoch 1400/2000 loss : 0.205618
Epoch 1500/2000 loss : 0.204529
Epoch 1600/2000 loss : 0.203481
Epoch 1700/2000 loss : 0.202486
Epoch 1800/2000 loss : 0.201539
Epoch 1900/2000 loss : 0.200634
Epoch 2000/2000 loss : 0.199770


In [20]:
# 훈련 여부 확인하기 
# 임의의 입력 [73, 82, 72]
new_var = torch.FloatTensor([[73, 82, 72]])
pred_y = model(new_var)
print(f"훈련 후 입력이 {new_var}일 때의 예측값: ", pred_y)

훈련 후 입력이 tensor([[73., 82., 72.]])일 때의 예측값:  tensor([[150.4079]], grad_fn=<AddmmBackward>)


In [21]:
import torch
import torch.nn as nn
import torch.nn.functional as F

from torch.utils.data import TensorDataset # 텐서 데이터셋
from torch.utils.data import DataLoader # 데이터로더

# TensorDataset은 기본적으로 텐서를 입력으로 받습니다. 텐서 형태로 데이터를 정의합니다.
x_train = torch.FloatTensor([[73, 80, 75],
                            [93, 88, 93],
                            [89, 91, 90],
                            [96, 98, 100],
                            [73, 66, 70]])
y_train = torch.FloatTensor([[152], [185], [180], [196], [142]])

# TensorDataset의 입력으로 사용하고 dataset으로 저장합니다.
dataset = TensorDataset(x_train, y_train)
"""
데이터로더는 기본적으로 2개의 인자를 입력받는다. 하나는 데이터셋, 미니 배치의 크기입니다. 
이때 미니 배치의 크기는 통상적으로 2의 배수를 사용합니다. (ex) 64, 128, 256...) 그리고 추가적으로 많이 사용되는 인자로 shuffle이 있습니다. 
shuffle=True를 선택하면 Epoch마다 데이터셋을 섞어서 데이터가 학습되는 순서를 바꿉니다.

사람도 같은 문제지를 계속 풀면 어느 순간 문제의 순서에 익숙해질 수 있습니다. 
예를 들어 어떤 문제지의 12번 문제를 풀면서, '13번 문제가 뭔지는 기억은 안 나지만 어제 풀었던 기억으로 정답은 5번이었던 것 같은데' 
하면서 문제 자체보단 순서에 익숙해질 수 있다는 것입니다. 그럴 때 문제지를 풀 때마다 문제 순서를 랜덤으로 바꾸면 도움이 될 겁니다. 
마찬가지로 모델이 데이터셋의 순서에 익숙해지는 것을 방지하여 학습할 때는 이 옵션을 True를 주는 것을 권장합니다.
"""
dataloader = DataLoader(dataset, batch_size = 2, shuffle = True)

# 이제 모델과 옵티마이저 설계
model = nn.Linear(3,1)
optimizer = torch.optim.SGD(model.parameters(), lr = 1e-5)

epochs_nb = 200
for epoch in range(epochs_nb + 1):
    for batch_idx, samples in enumerate(dataloader):
        
        #print(batch_idx)
        #print(samples)
        x_train, y_train = samples
        
        # H(x) 계산
        prediction = model(x_train)
        
        loss = F.mse_loss(prediction, y_train)
        
        # cost H(x) 계산
        optimizer.zero_grad() # 기울기를 0으로 초기화
        loss.backward() # loss 함수를 미분하여 기울기 계산
        optimizer.step() # w와 b 를 업데이트
        
        if epoch % 10 == 0:
            
            print("Epoch {:4d}/{} Batch {}/{} loss : {:.6f}".format(epoch, epochs_nb, batch_idx+1, len(dataloader), 
            loss.item()))

Epoch    0/200 Batch 1/3 loss : 46978.789062
Epoch    0/200 Batch 2/3 loss : 6497.784180
Epoch    0/200 Batch 3/3 loss : 5174.395996
Epoch   10/200 Batch 1/3 loss : 20.487284
Epoch   10/200 Batch 2/3 loss : 7.705010
Epoch   10/200 Batch 3/3 loss : 7.212080
Epoch   20/200 Batch 1/3 loss : 17.549288
Epoch   20/200 Batch 2/3 loss : 7.824885
Epoch   20/200 Batch 3/3 loss : 24.961105
Epoch   30/200 Batch 1/3 loss : 22.525852
Epoch   30/200 Batch 2/3 loss : 14.071042
Epoch   30/200 Batch 3/3 loss : 10.301792
Epoch   40/200 Batch 1/3 loss : 6.263861
Epoch   40/200 Batch 2/3 loss : 12.951877
Epoch   40/200 Batch 3/3 loss : 26.012863
Epoch   50/200 Batch 1/3 loss : 29.166300
Epoch   50/200 Batch 2/3 loss : 14.010695
Epoch   50/200 Batch 3/3 loss : 1.219263
Epoch   60/200 Batch 1/3 loss : 6.347510
Epoch   60/200 Batch 2/3 loss : 12.247962
Epoch   60/200 Batch 3/3 loss : 24.989016
Epoch   70/200 Batch 1/3 loss : 0.935088
Epoch   70/200 Batch 2/3 loss : 27.385311
Epoch   70/200 Batch 3/3 loss : 20

In [22]:
# 모델의 입력으로 임의의 값을 넣어 예측값을 확인

# 임의의 입력 값
test_val = torch.FloatTensor([[73, 80, 75]])

# 입력한 값 [73, 80, 75]에 대해서 예측값 y를 리턴받아서 pred_y에 저장
pred_y = model(test_val)
print("훈련 후 입력이 73 80 75일 때 예측값 : ", pred_y)

# 정답지 : 73 80 75 -> y 값이 152

훈련 후 입력이 73 80 75일 때 예측값 :  tensor([[154.5247]], grad_fn=<AddmmBackward>)
